{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "default.serviceAccountName" . }}
  labels:
{{ include "default.labels" . | indent 4 }}
{{- end -}}
